Add feature to sign in and sign up the user
bibekmaharjan/practitioner-management pull request #1
Opened 2023-05-15 03:37 UTC by bibekmaharjan

## Description

* Added sign in and sign up pages.
* Added protected route component to verify the authentication.

### Screenshot

![image](https://github.com/bibekmaharjan/practitioner-management/assets/30655695/be851d8c-91e7-4ae2-b85d-e823fac5ed51)

2023-05-16 04:38 UTC, sbimochan requested changes

2023-05-16 04:38 UTC, sbimochan commented on src/App.tsx
> +      localStorage.removeItem('token');
There can some errors while doing getItem from localStorage, can you store these actions in a localStorageUtil? The get method can have try...catch block with `void 0` in catch block

2023-05-16 04:38 UTC, sbimochan commented on src/assets/styles/components/_button.scss
> +.btn {
Use 2 space indent for consistency

2023-05-16 04:38 UTC, sbimochan commented on src/config.ts
> +    practitionerDetails: 'http://localhost:8080/practitioners/{id}',
create a separate constant for baseUrl that will retrieve value localhost from .env

2023-05-16 04:38 UTC, sbimochan commented on src/domain/misc/Config.ts
> +    practitionerDetails: string;
you sure that these are string?

2023-05-16 04:38 UTC, sbimochan commented on src/pages/Signin.tsx
> +      const response = await axios.post(config.endpoints.signIn, { email, password });
create some httpUtils

2023-05-16 04:38 UTC, sbimochan commented on src/pages/Signin.tsx
> +          placeholder="YOUR PASSWORD"
Don't use uppercase for placehoder. and MAIL can be changed to email id

2023-05-23 07:57 UTC, bibekmaharjan commented on src/domain/misc/Config.ts
> +    practitionerDetails: string;
Yes, endpoint values are expected string.

2023-05-26 10:45 UTC, merged