Added practitioner list page
bibekmaharjan/practitioner-management pull request #2
Opened 2023-05-15 06:16 UTC by bibekmaharjan

## Description

* Added practitioner list page where a list of practitioners can be fetched and listed.

### Screenshot:

![image](https://github.com/bibekmaharjan/practitioner-management/assets/30655695/e843d6d9-1a62-4809-b831-048f82979faf)

2023-05-16 08:51 UTC, sbimochan requested changes

2023-05-16 08:51 UTC, sbimochan commented on src/assets/styles/components/_loading.scss
> +            height: 7px;
Use of even number is recommended on such pixel. Also for other CSS codes

2023-05-16 08:51 UTC, sbimochan commented on src/assets/styles/components/_loading.scss
> +            left: 12px;
why are these all different for all 8 children?

2023-05-16 08:51 UTC, sbimochan commented on src/assets/styles/components/_loading.scss
> +  }
always add new line at end of file to prevent CRLF/LF issues, merge conflicts, text editor issues and follow consistency over all

2023-05-16 08:51 UTC, sbimochan commented on src/assets/styles/components/_practitionerListTable.scss
> +}
\n

2023-05-16 08:51 UTC, sbimochan commented on src/assets/styles/pages/_practitionerList.scss
> +}
you can infact add prettier and eslint that will auto add these

2023-05-16 08:51 UTC, sbimochan commented on src/components/common/Loading.tsx
> +        <div></div>
use padding/margin if you need gaps

2023-05-16 08:51 UTC, sbimochan commented on src/components/common/PractitionerListItem.tsx
> +  data: any;
don't use any. create data type for it

2023-05-16 08:51 UTC, sbimochan commented on src/components/common/PractitionerListItem.tsx
> +  const { data } = props;
Try this
```suggestion
const PractitionerListItem = ({data: PractitionerListItemProps, handleActionMenuClick} ) => {
  const { data } = props;
```

2023-05-16 08:51 UTC, sbimochan commented on src/components/common/PractitionerListItem.tsx
> +  const { data } = props;
can be removed

2023-05-16 08:51 UTC, sbimochan commented on src/components/common/PractitionerListItem.tsx
> +  const [isMenu, setIsMenu] = React.useState(false);
swap these lines. always put states on top

2023-05-16 08:51 UTC, sbimochan commented on src/components/common/PractitionerListItem.tsx
> +
unnecessary lines

2023-05-16 08:51 UTC, sbimochan commented on src/components/common/PractitionerListItem.tsx
> +          <img src={data.userImg as string} alt="" className="practitionerListTable__userInfo-img" />
add alt for accessibility

2023-05-16 08:51 UTC, sbimochan commented on src/components/common/PractitionerListItem.tsx
> +          <img src={dotsIcon} onClick={handleMenuClick} className="practitionerListTable__userInfo-dotsIcon" alt="" />
alt

2023-05-16 08:51 UTC, sbimochan commented on src/components/common/PractitionerListTable.tsx
> +  userData: any[];
set this up

2023-05-16 08:51 UTC, sbimochan commented on src/components/common/PractitionerListTable.tsx
> +  setUserData: (data: any) => void;
set data type for data

2023-05-16 08:51 UTC, sbimochan commented on src/components/common/PractitionerListTable.tsx
> +            {dummyData.map((data: any) => (
type it

2023-05-16 08:51 UTC, sbimochan commented on src/pages/PractitionerList.tsx
> +  const [userData, setUserData] = React.useState<any[]>([]);
type the state

2023-05-16 08:51 UTC, sbimochan commented on src/utils/interpolate.ts
> +export function interpolate(str: string, params: object | null): string {
write unit tests for these

2023-05-23 04:33 UTC, bibekmaharjan commented on src/assets/styles/components/_loading.scss
> +            left: 12px;
This was done for loading animation. It could be done using library but wanted to try without one.

2023-05-23 05:01 UTC, sbimochan commented on src/assets/styles/pages/_practitionerList.scss
> +}
@bibekmaharjan any updates?

2023-05-23 05:01 UTC, sbimochan commented on src/components/common/Loading.tsx
> +        <div></div>
.

2023-05-23 06:52 UTC, bibekmaharjan commented on src/assets/styles/pages/_practitionerList.scss
> +}
Yes, I have updated the prettier to add them.

2023-05-23 07:59 UTC, bibekmaharjan commented on src/components/common/Loading.tsx
> +        <div></div>
This is done for the loading component where the div are used for animation. Would it be better if I remove them and use library or other component instead?

2023-05-29 04:15 UTC, sbimochan commented on src/components/common/PractitionerListTable.tsx
> +  };
.

2023-05-29 04:16 UTC, sbimochan commented on src/components/common/PractitionerListTable.tsx
> +  React.useEffect(() => {
use same style. you were using useEffect in other files isn't it?

2023-05-29 04:24 UTC, sbimochan commented on src/utils/datetime.ts
> +export const formatDate = (date: Date | string | undefined, formatting: string): string => {
why support undefined? what does it return? I think 1980 something?

2023-05-29 12:32 UTC, merged